################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Src/bus_voltage_sensor.c \
C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Src/circle_limitation.c \
C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/MCSDK_v5.4.1/MotorControl/MCSDK/UILibrary/Src/dac_common_ui.c \
C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/MCSDK_v5.4.1/MotorControl/MCSDK/UILibrary/Src/dac_ui.c \
C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Src/digital_output.c \
C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Src/enc_align_ctrl.c \
C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Src/encoder_speed_pos_fdbk.c \
C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/MCSDK_v5.4.1/MotorControl/MCSDK/UILibrary/Src/frame_communication_protocol.c \
C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Src/mc_interface.c \
C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Src/mc_math.c \
C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Src/motor_power_measurement.c \
C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Src/ntc_temperature_sensor.c \
C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Src/open_loop.c \
C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Src/pid_regulator.c \
C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Src/pqd_motor_power_measurement.c \
C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Src/pwm_common.c \
C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Src/pwm_curr_fdbk.c \
C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/G4xx/Src/r3_2_g4xx_pwm_curr_fdbk.c \
C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Src/r_divider_bus_voltage_sensor.c \
C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Src/ramp_ext_mngr.c \
C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Src/speed_pos_fdbk.c \
C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Src/speed_torq_ctrl.c \
C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Src/state_machine.c \
C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/MCSDK_v5.4.1/MotorControl/MCSDK/UILibrary/Src/ui_irq_handler.c \
C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/MCSDK_v5.4.1/MotorControl/MCSDK/UILibrary/Src/usart_frame_communication_protocol.c \
C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Src/virtual_speed_sensor.c 

OBJS += \
./Middlewares/MotorControl/bus_voltage_sensor.o \
./Middlewares/MotorControl/circle_limitation.o \
./Middlewares/MotorControl/dac_common_ui.o \
./Middlewares/MotorControl/dac_ui.o \
./Middlewares/MotorControl/digital_output.o \
./Middlewares/MotorControl/enc_align_ctrl.o \
./Middlewares/MotorControl/encoder_speed_pos_fdbk.o \
./Middlewares/MotorControl/frame_communication_protocol.o \
./Middlewares/MotorControl/mc_interface.o \
./Middlewares/MotorControl/mc_math.o \
./Middlewares/MotorControl/motor_power_measurement.o \
./Middlewares/MotorControl/ntc_temperature_sensor.o \
./Middlewares/MotorControl/open_loop.o \
./Middlewares/MotorControl/pid_regulator.o \
./Middlewares/MotorControl/pqd_motor_power_measurement.o \
./Middlewares/MotorControl/pwm_common.o \
./Middlewares/MotorControl/pwm_curr_fdbk.o \
./Middlewares/MotorControl/r3_2_g4xx_pwm_curr_fdbk.o \
./Middlewares/MotorControl/r_divider_bus_voltage_sensor.o \
./Middlewares/MotorControl/ramp_ext_mngr.o \
./Middlewares/MotorControl/speed_pos_fdbk.o \
./Middlewares/MotorControl/speed_torq_ctrl.o \
./Middlewares/MotorControl/state_machine.o \
./Middlewares/MotorControl/ui_irq_handler.o \
./Middlewares/MotorControl/usart_frame_communication_protocol.o \
./Middlewares/MotorControl/virtual_speed_sensor.o 

C_DEPS += \
./Middlewares/MotorControl/bus_voltage_sensor.d \
./Middlewares/MotorControl/circle_limitation.d \
./Middlewares/MotorControl/dac_common_ui.d \
./Middlewares/MotorControl/dac_ui.d \
./Middlewares/MotorControl/digital_output.d \
./Middlewares/MotorControl/enc_align_ctrl.d \
./Middlewares/MotorControl/encoder_speed_pos_fdbk.d \
./Middlewares/MotorControl/frame_communication_protocol.d \
./Middlewares/MotorControl/mc_interface.d \
./Middlewares/MotorControl/mc_math.d \
./Middlewares/MotorControl/motor_power_measurement.d \
./Middlewares/MotorControl/ntc_temperature_sensor.d \
./Middlewares/MotorControl/open_loop.d \
./Middlewares/MotorControl/pid_regulator.d \
./Middlewares/MotorControl/pqd_motor_power_measurement.d \
./Middlewares/MotorControl/pwm_common.d \
./Middlewares/MotorControl/pwm_curr_fdbk.d \
./Middlewares/MotorControl/r3_2_g4xx_pwm_curr_fdbk.d \
./Middlewares/MotorControl/r_divider_bus_voltage_sensor.d \
./Middlewares/MotorControl/ramp_ext_mngr.d \
./Middlewares/MotorControl/speed_pos_fdbk.d \
./Middlewares/MotorControl/speed_torq_ctrl.d \
./Middlewares/MotorControl/state_machine.d \
./Middlewares/MotorControl/ui_irq_handler.d \
./Middlewares/MotorControl/usart_frame_communication_protocol.d \
./Middlewares/MotorControl/virtual_speed_sensor.d 


# Each subdirectory must supply rules for building sources it contributes
Middlewares/MotorControl/bus_voltage_sensor.o: C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Src/bus_voltage_sensor.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32G431xx -c -I../../../Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/G4xx/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/UILibrary/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/SystemDriveParams -I../../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../../Drivers/CMSIS/Include -O3 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/MotorControl/bus_voltage_sensor.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/MotorControl/circle_limitation.o: C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Src/circle_limitation.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32G431xx -c -I../../../Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/G4xx/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/UILibrary/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/SystemDriveParams -I../../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../../Drivers/CMSIS/Include -O3 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/MotorControl/circle_limitation.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/MotorControl/dac_common_ui.o: C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/MCSDK_v5.4.1/MotorControl/MCSDK/UILibrary/Src/dac_common_ui.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32G431xx -c -I../../../Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/G4xx/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/UILibrary/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/SystemDriveParams -I../../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../../Drivers/CMSIS/Include -O3 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/MotorControl/dac_common_ui.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/MotorControl/dac_ui.o: C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/MCSDK_v5.4.1/MotorControl/MCSDK/UILibrary/Src/dac_ui.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32G431xx -c -I../../../Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/G4xx/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/UILibrary/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/SystemDriveParams -I../../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../../Drivers/CMSIS/Include -O3 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/MotorControl/dac_ui.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/MotorControl/digital_output.o: C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Src/digital_output.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32G431xx -c -I../../../Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/G4xx/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/UILibrary/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/SystemDriveParams -I../../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../../Drivers/CMSIS/Include -O3 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/MotorControl/digital_output.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/MotorControl/enc_align_ctrl.o: C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Src/enc_align_ctrl.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32G431xx -c -I../../../Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/G4xx/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/UILibrary/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/SystemDriveParams -I../../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../../Drivers/CMSIS/Include -O3 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/MotorControl/enc_align_ctrl.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/MotorControl/encoder_speed_pos_fdbk.o: C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Src/encoder_speed_pos_fdbk.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32G431xx -c -I../../../Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/G4xx/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/UILibrary/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/SystemDriveParams -I../../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../../Drivers/CMSIS/Include -O3 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/MotorControl/encoder_speed_pos_fdbk.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/MotorControl/frame_communication_protocol.o: C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/MCSDK_v5.4.1/MotorControl/MCSDK/UILibrary/Src/frame_communication_protocol.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32G431xx -c -I../../../Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/G4xx/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/UILibrary/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/SystemDriveParams -I../../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../../Drivers/CMSIS/Include -O3 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/MotorControl/frame_communication_protocol.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/MotorControl/mc_interface.o: C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Src/mc_interface.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32G431xx -c -I../../../Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/G4xx/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/UILibrary/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/SystemDriveParams -I../../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../../Drivers/CMSIS/Include -O3 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/MotorControl/mc_interface.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/MotorControl/mc_math.o: C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Src/mc_math.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32G431xx -c -I../../../Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/G4xx/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/UILibrary/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/SystemDriveParams -I../../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../../Drivers/CMSIS/Include -O3 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/MotorControl/mc_math.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/MotorControl/motor_power_measurement.o: C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Src/motor_power_measurement.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32G431xx -c -I../../../Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/G4xx/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/UILibrary/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/SystemDriveParams -I../../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../../Drivers/CMSIS/Include -O3 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/MotorControl/motor_power_measurement.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/MotorControl/ntc_temperature_sensor.o: C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Src/ntc_temperature_sensor.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32G431xx -c -I../../../Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/G4xx/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/UILibrary/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/SystemDriveParams -I../../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../../Drivers/CMSIS/Include -O3 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/MotorControl/ntc_temperature_sensor.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/MotorControl/open_loop.o: C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Src/open_loop.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32G431xx -c -I../../../Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/G4xx/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/UILibrary/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/SystemDriveParams -I../../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../../Drivers/CMSIS/Include -O3 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/MotorControl/open_loop.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/MotorControl/pid_regulator.o: C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Src/pid_regulator.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32G431xx -c -I../../../Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/G4xx/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/UILibrary/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/SystemDriveParams -I../../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../../Drivers/CMSIS/Include -O3 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/MotorControl/pid_regulator.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/MotorControl/pqd_motor_power_measurement.o: C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Src/pqd_motor_power_measurement.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32G431xx -c -I../../../Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/G4xx/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/UILibrary/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/SystemDriveParams -I../../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../../Drivers/CMSIS/Include -O3 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/MotorControl/pqd_motor_power_measurement.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/MotorControl/pwm_common.o: C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Src/pwm_common.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32G431xx -c -I../../../Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/G4xx/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/UILibrary/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/SystemDriveParams -I../../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../../Drivers/CMSIS/Include -O3 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/MotorControl/pwm_common.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/MotorControl/pwm_curr_fdbk.o: C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Src/pwm_curr_fdbk.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32G431xx -c -I../../../Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/G4xx/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/UILibrary/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/SystemDriveParams -I../../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../../Drivers/CMSIS/Include -O3 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/MotorControl/pwm_curr_fdbk.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/MotorControl/r3_2_g4xx_pwm_curr_fdbk.o: C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/G4xx/Src/r3_2_g4xx_pwm_curr_fdbk.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32G431xx -c -I../../../Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/G4xx/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/UILibrary/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/SystemDriveParams -I../../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../../Drivers/CMSIS/Include -O3 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/MotorControl/r3_2_g4xx_pwm_curr_fdbk.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/MotorControl/r_divider_bus_voltage_sensor.o: C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Src/r_divider_bus_voltage_sensor.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32G431xx -c -I../../../Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/G4xx/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/UILibrary/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/SystemDriveParams -I../../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../../Drivers/CMSIS/Include -O3 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/MotorControl/r_divider_bus_voltage_sensor.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/MotorControl/ramp_ext_mngr.o: C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Src/ramp_ext_mngr.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32G431xx -c -I../../../Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/G4xx/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/UILibrary/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/SystemDriveParams -I../../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../../Drivers/CMSIS/Include -O3 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/MotorControl/ramp_ext_mngr.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/MotorControl/speed_pos_fdbk.o: C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Src/speed_pos_fdbk.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32G431xx -c -I../../../Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/G4xx/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/UILibrary/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/SystemDriveParams -I../../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../../Drivers/CMSIS/Include -O3 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/MotorControl/speed_pos_fdbk.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/MotorControl/speed_torq_ctrl.o: C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Src/speed_torq_ctrl.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32G431xx -c -I../../../Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/G4xx/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/UILibrary/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/SystemDriveParams -I../../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../../Drivers/CMSIS/Include -O3 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/MotorControl/speed_torq_ctrl.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/MotorControl/state_machine.o: C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Src/state_machine.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32G431xx -c -I../../../Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/G4xx/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/UILibrary/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/SystemDriveParams -I../../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../../Drivers/CMSIS/Include -O3 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/MotorControl/state_machine.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/MotorControl/ui_irq_handler.o: C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/MCSDK_v5.4.1/MotorControl/MCSDK/UILibrary/Src/ui_irq_handler.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32G431xx -c -I../../../Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/G4xx/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/UILibrary/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/SystemDriveParams -I../../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../../Drivers/CMSIS/Include -O3 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/MotorControl/ui_irq_handler.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/MotorControl/usart_frame_communication_protocol.o: C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/MCSDK_v5.4.1/MotorControl/MCSDK/UILibrary/Src/usart_frame_communication_protocol.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32G431xx -c -I../../../Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/G4xx/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/UILibrary/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/SystemDriveParams -I../../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../../Drivers/CMSIS/Include -O3 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/MotorControl/usart_frame_communication_protocol.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/MotorControl/virtual_speed_sensor.o: C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Src/virtual_speed_sensor.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32G431xx -c -I../../../Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/G4xx/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/UILibrary/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/SystemDriveParams -I../../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../../Drivers/CMSIS/Include -O3 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/MotorControl/virtual_speed_sensor.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

