################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/Src/app_freertos.c \
C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/Src/main.c \
C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/Src/mc_api.c \
C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/Src/mc_config.c \
C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/Src/mc_parameters.c \
C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/Src/mc_tasks.c \
C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/Src/motor_control_protocol.c \
C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/Src/motorcontrol.c \
C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/Src/regular_conversion_manager.c \
C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/Src/stm32g4xx_hal_msp.c \
C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/Src/stm32g4xx_hal_timebase_tim.c \
C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/Src/stm32g4xx_it.c \
C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/Src/stm32g4xx_mc_it.c \
C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/Src/ui_task.c \
C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/Src/user_interface.c 

OBJS += \
./Application/User/app_freertos.o \
./Application/User/main.o \
./Application/User/mc_api.o \
./Application/User/mc_config.o \
./Application/User/mc_parameters.o \
./Application/User/mc_tasks.o \
./Application/User/motor_control_protocol.o \
./Application/User/motorcontrol.o \
./Application/User/regular_conversion_manager.o \
./Application/User/stm32g4xx_hal_msp.o \
./Application/User/stm32g4xx_hal_timebase_tim.o \
./Application/User/stm32g4xx_it.o \
./Application/User/stm32g4xx_mc_it.o \
./Application/User/ui_task.o \
./Application/User/user_interface.o 

C_DEPS += \
./Application/User/app_freertos.d \
./Application/User/main.d \
./Application/User/mc_api.d \
./Application/User/mc_config.d \
./Application/User/mc_parameters.d \
./Application/User/mc_tasks.d \
./Application/User/motor_control_protocol.d \
./Application/User/motorcontrol.d \
./Application/User/regular_conversion_manager.d \
./Application/User/stm32g4xx_hal_msp.d \
./Application/User/stm32g4xx_hal_timebase_tim.d \
./Application/User/stm32g4xx_it.d \
./Application/User/stm32g4xx_mc_it.d \
./Application/User/ui_task.d \
./Application/User/user_interface.d 


# Each subdirectory must supply rules for building sources it contributes
Application/User/app_freertos.o: C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/Src/app_freertos.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32G431xx -c -I../../../Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/G4xx/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/UILibrary/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/SystemDriveParams -I../../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../../Drivers/CMSIS/Include -O3 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Application/User/app_freertos.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/main.o: C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/Src/main.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32G431xx -c -I../../../Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/G4xx/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/UILibrary/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/SystemDriveParams -I../../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../../Drivers/CMSIS/Include -O3 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Application/User/main.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/mc_api.o: C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/Src/mc_api.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32G431xx -c -I../../../Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/G4xx/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/UILibrary/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/SystemDriveParams -I../../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../../Drivers/CMSIS/Include -O3 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Application/User/mc_api.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/mc_config.o: C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/Src/mc_config.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32G431xx -c -I../../../Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/G4xx/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/UILibrary/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/SystemDriveParams -I../../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../../Drivers/CMSIS/Include -O3 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Application/User/mc_config.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/mc_parameters.o: C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/Src/mc_parameters.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32G431xx -c -I../../../Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/G4xx/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/UILibrary/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/SystemDriveParams -I../../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../../Drivers/CMSIS/Include -O3 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Application/User/mc_parameters.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/mc_tasks.o: C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/Src/mc_tasks.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32G431xx -c -I../../../Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/G4xx/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/UILibrary/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/SystemDriveParams -I../../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../../Drivers/CMSIS/Include -O3 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Application/User/mc_tasks.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/motor_control_protocol.o: C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/Src/motor_control_protocol.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32G431xx -c -I../../../Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/G4xx/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/UILibrary/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/SystemDriveParams -I../../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../../Drivers/CMSIS/Include -O3 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Application/User/motor_control_protocol.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/motorcontrol.o: C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/Src/motorcontrol.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32G431xx -c -I../../../Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/G4xx/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/UILibrary/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/SystemDriveParams -I../../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../../Drivers/CMSIS/Include -O3 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Application/User/motorcontrol.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/regular_conversion_manager.o: C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/Src/regular_conversion_manager.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32G431xx -c -I../../../Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/G4xx/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/UILibrary/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/SystemDriveParams -I../../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../../Drivers/CMSIS/Include -O3 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Application/User/regular_conversion_manager.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/stm32g4xx_hal_msp.o: C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/Src/stm32g4xx_hal_msp.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32G431xx -c -I../../../Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/G4xx/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/UILibrary/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/SystemDriveParams -I../../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../../Drivers/CMSIS/Include -O3 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Application/User/stm32g4xx_hal_msp.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/stm32g4xx_hal_timebase_tim.o: C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/Src/stm32g4xx_hal_timebase_tim.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32G431xx -c -I../../../Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/G4xx/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/UILibrary/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/SystemDriveParams -I../../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../../Drivers/CMSIS/Include -O3 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Application/User/stm32g4xx_hal_timebase_tim.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/stm32g4xx_it.o: C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/Src/stm32g4xx_it.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32G431xx -c -I../../../Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/G4xx/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/UILibrary/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/SystemDriveParams -I../../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../../Drivers/CMSIS/Include -O3 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Application/User/stm32g4xx_it.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/stm32g4xx_mc_it.o: C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/Src/stm32g4xx_mc_it.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32G431xx -c -I../../../Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/G4xx/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/UILibrary/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/SystemDriveParams -I../../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../../Drivers/CMSIS/Include -O3 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Application/User/stm32g4xx_mc_it.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/ui_task.o: C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/Src/ui_task.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32G431xx -c -I../../../Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/G4xx/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/UILibrary/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/SystemDriveParams -I../../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../../Drivers/CMSIS/Include -O3 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Application/User/ui_task.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/user_interface.o: C:/2_Development/2-\ Sumo\ Bot/Programing/ESC/ESC_Drive_Motors/Src/user_interface.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32G431xx -c -I../../../Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/Any/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/MCLib/G4xx/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/UILibrary/Inc -I../../../MCSDK_v5.4.1/MotorControl/MCSDK/SystemDriveParams -I../../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../../Drivers/CMSIS/Include -O3 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Application/User/user_interface.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

